### ISSUE TITLE
Using expressions as statements fails in the C# backend

### ISSUE THREAD

**Issue by kharai-tor** [TKharaishvili/Ephemera#9]
Transpiling any expression except function invocation expressions to C# and trying to run it fails with an error: `CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement`.

This obviously was an oversight. I see 2 possible ways of dealing with it, either I should fix the transpilation or this should be considered an error in Ephemera as well. I'm leaning towards the latter. I hope that won't be a problem if I ever attempt building an interactive experience.

**Comment by TKharaishvili** [comment]
Fixed here - https://github.com/TKharaishvili/Ephemera/commit/23a2240b1ec8ed5f2db12b40b28ea3def838bd4f

**Comment by kharai-tor** [comment]
Fixed here - https://github.com/TKharaishvili/Ephemera/commit/23a2240b1ec8ed5f2db12b40b28ea3def838bd4f
